### ISSUE TITLE
Error sending message

### ISSUE THREAD

**Issue by rcsmota** [Cacti/plugin_monitor#66]
Hi;

I'm get the follow error when device is down and monitor plugin send mail.

11/05/2018  13:25:20 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/monitor/poller_monitor.php: 92  monitor_uptime_checker)(/plugins/monitor/poller_monitor.php: 233  process_reboot_email)(/plugins/monitor/poller_monitor.php: 305  process_send_email)(/plugins/monitor/poller_monitor.php: 490  CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
11/05/2018 13:25:20 - ERROR PHP NOTICE in  Plugin 'monitor':  Undefined variable: warn_hosts in file:  /opt/cacti/plugins/monitor/poller_monitor.php  on line: 490
11/05/2018 13:25:20 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/monitor/poller_monitor.php: 92  monitor_uptime_checker)(/plugins/monitor/poller_monitor.php: 233  process_reboot_email)(/plugins/monitor/poller_monitor.php: 305  process_send_email)(/plugins/monitor/poller_monitor.php: 489  CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
11/05/2018 13:25:20 - ERROR PHP NOTICE in  Plugin 'monitor':  Undefined variable: alert_hosts in file:  /opt/cacti/plugins/monitor/poller_monitor.php  on line: 489

I get the mail without any problems but all time thi message is show in cacti log for all mails configure in notification list.

MAILER Mail Successfully Sent to 'xxxxx@xxxxxx.net', Subject: 'Cacti Device Reboot Nofication' 

This is what I have in lines 489 and 490

(sizeof($alert_hosts) ? sizeof($alert_hosts) . ' Alert Notifications':'') .
                        (sizeof($warn_hosts) ? (sizeof($alert_hosts) ? ', and ':'') .

I running cacti Version 1.1.38 on Debian 9

Thanks;

**Comment by netniV** [comment]
What version of monitor are you running?

**Comment by netniV** [comment]
This should now be corrected in the development version of monitor.

**Comment by rcsmota** [comment]
Hi @netniV 
I'm running 2.3.4 monitor version. Updating to 2.3.5 right now

**Comment by netniV** [comment]
Development will likely still show 2.3.4 but as long as you are using the latest code, you should see the above change which includes $status

**Comment by rcsmota** [comment]
Exactly, when I updated still show likely 2.3.4 version, but I force a "fake" shutdown and all e-mail was sent without errors.
I think everything is ok now. 

Thanks @netniV
